#!/bin/bash

function setup_hostname {
    echocolor "Setup /etc/hostname"
    sleep 3
    if [ "$1" == "controller" ]; then
        echo "CTL" > /etc/hostname
        hostname -F /etc/hostname
    elif ["$1" == "compute" ]; then
        echo "COM1" > /etc/hostname
        hostname -F /etc/hostname
    else
        echocolor "Sai roi"
    fi

}

setup_hostname $1